name: Build Flutter App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.0'  # اپنی Flutter ورژن یہاں لکھیں

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release
